state:
    id: state
    module_path: langgraph_rags.rag_about_ragator.rag_state
    class_name: RagState

entry_point: get_user_metadata

nodes:
  - id: classify_question
    module_path: langgraph_rags.rag_about_ragator.nodes.classify_question
    function_name: main

  - id: generate_static_answer
    module_path: langgraph_rags.rag_about_ragator.nodes.get_static_answer
    function_name: main

  - id: retrieve_documents
    module_path: langgraph_rags.rag_about_ragator.nodes.retrieve_documents
    function_name: main

  - id: generate_llm_answer
    module_path: langgraph_rags.rag_about_ragator.nodes.generate_llm_answer
    function_name: main

edges:
  - from_node: get_user_metadata
    to_node: classify_question

  - from_node: classify_question
    condition:
        id: question_classification
        module_path: langgraph_rags.rag_about_ragator.routers.question_classification
        function_name: main
    mapping:
      OFF_TOPIC: generate_static_answer
      ON_TOPIC: retrieve_documents

### STATIC ANSWER
  - from_node: generate_static_answer
    to_node: __end__

### RETRIEVAL AUGMENTED GENERATION
  - from_node: retrieve_documents
    to_node: generate_llm_answer

  - from_node: generate_llm_answer
    to_node: __end__
