sources:
  - https://langchain-ai.github.io/langgraph/
  - https://python-client.qdrant.tech/
max_pages_per_sources:  100

embedding_model:
    name: text-embedding-3-large
    type: openai
    chunk_size: 500
    chunk_overlap: 50

vector_store:
    module: src.retrieval.vector_stores.qdrant_store
    class: QdrantStore
    collection_name: "ragator-collection"
